version: "3.3"

services:

  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    ports:
      - 27017:27017 

  node-api-demo:
    build: 
      context: .
    container_name: node-api-demo
    restart: always
    ports:
      - "8080:8080"
    links:
      - mongodb
    environment:
      - DB_URI=mongodb+srv://pass0123:2cSl5qyowFccQcde@cluster0.feek4.mongodb.net/test
      - TEST_DB_URI=mongodb+srv://pass0123:IksWcr10AG18xvOu@cluster0.ocqtj.mongodb.net/test
